### ISSUE TITLE
html email tpl translates into line breaks

### ISSUE THREAD

**Issue by devidw** [HandyPlugins/magic-login#12]
https://github.com/HandyPlugins/magic-login/blob/72bff64cd2f43735e89137106cecaeb0bb182b2a/includes/login.php#L156-L158

Is this desired?

Shouldn't it be the other way around, only add line breaks when there is no HTML markup in the mail?

Otherwise, each line break in the markup adds a visual line break, which adds a lot of empty space into the email and the layout breaks.

**Comment by mustafauysal** [comment]
@devidw Yeah, it would be better to add a line break only if the given email content doesn't contain HTML tags. I'm going to look into this.

**Comment by mustafauysal** [comment]
@devidw fixed in version 1.5 (I just released) ref: ccb2122d114af5309719d12df5708733118b3072
