### ISSUE TITLE
Compatibility: Theme my login 

### ISSUE THREAD

**Issue by mustafauysal** [HandyPlugins/magic-login#7]
Make it compatible with - https://wordpress.org/plugins/theme-my-login/

**Comment by airplanenoise** [comment]
@mustafauysal thanks for doing that. if anybody has a workaround, I'll take it.

**Comment by mustafauysal** [comment]
@airplanenoise It should be working if you remove `'wp-login.php' !== $pagenow` control in `handle_login_request()` function https://github.com/HandyPlugins/magic-login/blob/1.2.1/includes/login.php#L231

The root cause of the issue "theme my login" sets a different $pagenow and it leads to failing the automatic login process.

**Comment by techlawyers** [comment]
Maybe @jfarthing84 can help us out here?

**Comment by jfarthing84** [comment]
@mustafauysal TML does not modify $pagenow. If you mean $pagenow is not wp-login.php, because it literally isn't, this is true.

I would suggest this plugin use the `login_init` hook instead of `init`. Then, the `wp-login.php !== $pagenow` would not be needed.

**Comment by techlawyers** [comment]
> I would suggest this plugin use the `login_init` hook instead of `init`. Then, the `wp-login.php !== $pagenow` would not be needed.

@jfarthing84 Thanks for your quick reply.

@mustafauysal Is it possible to implement it?

**Comment by mustafauysal** [comment]
@jfarthing84 Thanks for the input. I agree, `login_init` seems a better solution. However, I'm not sure all the plugins that modify the login URL have implemented the hook properly, perhaps passing a custom parameter and checking it would be better.

@techlawyers Yep! The next version (which I'm planning the release within 2 weeks will be compatible with TML)
