### ISSUE TITLE
sending multiple emails

### ISSUE THREAD

**Issue by mustafauysal** [HandyPlugins/magic-login#8]
It's a weird case, but when a page has more than one magic login form, it sends multiple emails simultaneously. This should be avoided.

**Comment by mustafauysal** [comment]
Reproducing step: add more than one magic login shortcode to a page. Or use magic login block and shortcode at the same time

**Comment by techlawyers** [comment]
Perhaps a context: if Magic Login via shortcode is on a page with a TML via shortcode, clicking the Magic Login form button will also trigger TML's form.
